config/routes.rb
Drdannicoll::Application.routes.draw do

  root :to => 'pages#home'

  get '/home' => 'pages#home'
  get '/about' => 'pages#about'

  namespace :admin do
    get  'sign-in' => 'sessions#new', as: 'sign_in'
    post 'sign-in' => 'sessions#create'
    get  'sign-out' => 'sessions#destroy', as: 'sign_out'

    resources :questions, :articles, :answers, module: nil
    root :to => 'answers#index'
  end

  resources :categories do
    resources :articles, :answers, except: [:new, :edit] do
      get 'search', :on => :collection
    end
  end

  resources :questions, :articles, :answers do
    get 'search', on: :collection
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title, :category_id

  belongs_to :category

  # Number of articles per page
  self.per_page = 9

  # Search
  include PgSearch
  pg_search_scope :search_by_title,
                  :against => [:title, :content],
                  :using => {
                    :tsearch => { prefix: true }
                  }

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorize, except: [:index, :show, :search]
  before_filter :add_body_class, except: [:create, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @title = 'Articles'
    if params[:category_id]
      @category = Category.find params[:category_id]
      @articles = @category.articles.order(:title).paginate page: params[:page]
    else
      @articles = Article.order(:title).paginate page: params[:page]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @title = "Article ##{@article.id}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @title = 'New Article'
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @body_class = 'articles'
    @article = Article.find(params[:id])
    @title = "Article ##{@article.id}"
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  def search
    @showAll = false
    @maxArticles = Article.count
    query = params[:q]
    if params[:category_id]
      @category = Category.find params[:category_id]
      @articles = @category.articles
    else
      @articles = Article
    end

    if query.empty?
      @showAll = true
      @articles = @articles.paginate page: 1
    else
      @articles = @articles.search_by_title(query).paginate page: 1
    end

    @noResults = @articles.size < 1
    respond_to :js
  end

  def add_body_class
    @body_class = 'articles'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
%article.article
  = link_to category_article_path(article.category, article) do
    %h1= article.title
    .markdown
      %p= redcarpet truncate article.content, length: 400

app/views/articles/_form.html.haml
= semantic_form_for @article do |f|
  = f.inputs do
    .two-column
      = f.input :title
      = f.input :category, include_blank: false
    = f.input :content, input_html: { rows: 7 }

  = f.actions do
    = f.action :submit

app/views/articles/edit.html.haml
%section.header
  .wrapper
    %h2 Editing Article

%section.content.edit
  .wrapper
    %p.back= link_to '‹‹ Go back', category_articles_path(@article.category)
    = render 'form'
    = render 'partials/markdown_legend'

app/views/articles/index.html.haml
%section.header
  .wrapper
    %h2 Articles
    %p
      Below you can find various articles relating to obstetrics, infants/children,
      adolescents, and adult medicine. These articles can answer many questions
      not covered in the frequently asked questions section of this site.

%section.content.index
  .wrapper
    .categories
      - Category.all.each do |category|
        %div= link_to_unless_current category.title, category_articles_path(category)

    - if @category
      = render 'partials/search_form', search_path: search_category_articles_path(@category)
    - else
      = render 'partials/search_form', search_path: search_articles_path

    = render @articles
    = will_paginate @articles

:javascript
  articles.init()
  window.search = new Search('#search')

app/views/articles/new.html.haml
%section.header
  .wrapper
    %h2 Create a new article

%section.content.new
  .wrapper
    %p.back= link_to '‹‹ Go back', articles_path
    = render 'form'
    = render 'partials/markdown_legend'

app/views/articles/search.js.haml
var articles = "#{ escape_javascript(render @articles) }";
var $container = $('.content').children('.wrapper');

$container.find('.pagination').css('visibility','hidden');
$container.find('article, h1.no-results').remove();

if (#{@noResults}) {
$container.append('<h1 class="no-results">No results</h1>');
} else {
if (#{@showAll}) $container.find('.pagination').css('visibility','visible');
$container.find('form').after(articles);
$container.children('.article').first().addClass('active');
}

app/views/articles/show.html.haml
%section.header
  .wrapper

%section.content.show
  .wrapper
    - if @article.category
      %p.back= link_to '‹‹ Go back', category_articles_path(@article.category)
    - else
      %p.back= link_to '‹‹ Go back', articles_path

    %h1= @article.title
    .markdown
      %p= redcarpet @article.content