config/routes.rb
Drdannicoll::Application.routes.draw do

  root :to => 'pages#home'

  get '/home' => 'pages#home'
  get '/about' => 'pages#about'

  namespace :admin do
    get  'sign-in' => 'sessions#new', as: 'sign_in'
    post 'sign-in' => 'sessions#create'
    get  'sign-out' => 'sessions#destroy', as: 'sign_out'

    resources :questions, :articles, :answers, module: nil
    root :to => 'answers#index'
  end

  resources :categories do
    resources :articles, :answers, except: [:new, :edit] do
      get 'search', :on => :collection
    end
  end

  resources :questions, :articles, :answers do
    get 'search', on: :collection
  end

end

app/views/partials/_control_panel.html.haml
.control_panel
  .wrapper
    = link_to 'Create New FAQ', new_answer_path
    = link_to 'Create New Article', new_article_path

    - if @article and @article.id?
      = link_to 'Edit This Article', edit_article_path(@article), class: 'edit'
      = link_to 'Delete This Article', @article, method: 'delete', confirm: 'Are you sure?', class: 'delete'

    - if @answer and @answer.id?
      = link_to 'Edit This Answer', edit_answer_path(@answer), class: 'edit'
      = link_to 'Delete This Answer', @answer, method: 'delete', confirm: 'Are you sure?', class: 'delete'

app/views/partials/_footer.html.haml
%footer
  .stitched-border
  .wrapper
    %section.blurb
      .portrait
        = image_tag 'dannicoll.jpg', alt: 'Dr. Nicoll'

      %p
        Warren Clinic 
        %br
        10507 East 91st Street
        %br 
        Tulsa, OK 74133
        %br
        Suite 550

      %p
        %span 
          Make an appointment
        %br
        918-307-3160

    %p.pStyle
      %a Dr. Nicoll
      %span
        is currently located in the Bishop Building on the campus of St Francis
        South. He has been in Tulsa, Oklahoma since 2003. Dr Nicoll is board certified in
        Family Medicine with an emphasis on Women's Health and Obstetrics.

    = semantic_form_for Question.new do |f|
      %input{ name: 'path', type: 'hidden', value: request.fullpath }
      = f.inputs do
        .two-column
          = f.input :name, placeholder: 'Your Name'
          = f.input :email, placeholder: 'Email Address'
        = f.input :message, input_html: { rows: 2 }
      = f.actions do
        = f.action :submit, label: 'Ask a Question'

  .stitched-border
  .foot
    .wrapper
      %p.copyright
        © 2012
        = link_to 'Dr. Dan Nicoll.', admin_sign_in_path
        All Rights Reserved.
      %p.crafted= link_to 'crafted by cleverCode', 'http://clevercode.net/'

app/views/partials/_header.html.haml
%header
  .wrapper
    %h1
      = link_to 'Dr. Daniel Nicoll, DO', root_path
      %aside |&nbsp;&nbsp;&nbsp;Family Practice & Obstetrics
    %nav
      = link_to 'Home', root_path, class: @body_class == 'home' ? 'current' : ''
      = link_to 'About', about_path, class: @body_class == 'about' ? 'current' : ''
      = link_to 'FAQ', answers_path, class: @body_class == 'faq' ? 'current' : ''
      = link_to 'Articles', articles_path, class: @body_class == 'articles' ? 'current' : ''

      - if current_user
        = link_to 'Questions', questions_path, class: @body_class == 'questions' ? 'current' : ''
        = link_to 'Sign Out', admin_sign_out_path

app/views/partials/_markdown_legend.html.haml
%section.legend
  %h1 Helpful Hints
  %p You can use the following to help make your content a bit easier to read.
  %p # This is a main title
  %p ## This is a subtitle
  %p 1. This is a numbered list item
  %p *&nbsp;&nbsp;This is a bulleted list item
  %p *This text will be italic*
  %p **This text will be bold**

app/views/partials/_search_form.html.haml
= form_tag search_path, method: 'get', id: 'search', remote: true do
  = search_field_tag :q, nil, results: 5, placeholder: 'Search...', autocomplete: 'off'