config/routes.rb
Drdannicoll::Application.routes.draw do

  root :to => 'pages#home'

  get '/home' => 'pages#home'
  get '/about' => 'pages#about'

  namespace :admin do
    get  'sign-in' => 'sessions#new', as: 'sign_in'
    post 'sign-in' => 'sessions#create'
    get  'sign-out' => 'sessions#destroy', as: 'sign_out'

    resources :questions, :articles, :answers, module: nil
    root :to => 'answers#index'
  end

  resources :categories do
    resources :articles, :answers, except: [:new, :edit] do
      get 'search', :on => :collection
    end
  end

  resources :questions, :articles, :answers do
    get 'search', on: :collection
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :question, :category_id

  belongs_to :category

  # Number of articles per page
  self.per_page = 10

  # Search
  include PgSearch
  pg_search_scope :search_by_question,
                  :against => :question,
                  :using => {
                    :tsearch => { prefix: true }
                  }

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authorize, except: [:index, :show, :search]
  before_filter :add_body_class, except: [:create, :update, :destroy]

  def index
    @title = 'FAQ'
    if params[:category_id]
      @category = Category.find params[:category_id]
      @answers = @category.answers.paginate page: params[:page]
    else
      @answers = Answer.paginate page: params[:page]
    end
  end

  def show
    @answer = Answer.find(params[:id])
    @title = "Answer ##{@answer.id}"

    respond_to do |format|
      format.html
      format.json { render json: @answer }
    end
  end

  def new
    @title = 'New FAQ'
    @answer = Answer.new

    respond_to do |format|
      format.html
      format.json { render json: @answer }
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    @title = "Answer ##{@answer.id}"
  end

  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  def search
    @showAll = false
    @maxAnswers = Answer.count
    query = params[:q]
    if params[:category_id]
      @category = Category.find params[:category_id]
      @answers = @category.answers
    else
      @answers = Answer
    end

    if query.empty?
      @showAll = true
      @answers = @answers.paginate page: 1
    else
      @answers = @answers.search_by_question(query).paginate page: 1
    end

    @noResults = @answers.size < 1
    respond_to :js
  end

  def add_body_class
    @body_class = 'faq'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
%article.answer
  %h1
    = answer.question

  .markdown
    %p= redcarpet truncate answer.content, length: 400
    %p.read-more= link_to 'Read more ››', category_answer_path(answer.category, answer)

app/views/answers/_form.html.haml
= semantic_form_for @answer do |f|
  = f.inputs do
    .two-column
      = f.input :question
      = f.input :category, include_blank: false
    = f.input :content, label: 'Answer', input_html: { rows: 7 }

  = f.actions do
    = f.action :submit

app/views/answers/edit.html.haml
%section.header
  .wrapper
    %h2 Edit Question/Answer

%section.content.edit
  .wrapper
    %p.back= link_to '‹‹ Go back', category_answers_path(@answer.category)
    = render 'form'
    = render 'partials/markdown_legend'

app/views/answers/index.html.haml
%section.header
  .wrapper
    %h2 Frequently Asked Questions
    %p
      Below is a list of the most frequently asked questions. The majority of
      these questions relate to prenatal care, and should be used as a reference
      throughout your pregnancy. Keep in mind that even though this information
      is intended for the patients of Saint Francis Hopsital in Oklahoma, it can
      be helpful for anyone.

%section.content.index
  .wrapper
    .categories
      - Category.all.each do |category|
        %div= link_to_unless_current category.title, category_answers_path(category)

    - if @category
      = render 'partials/search_form', search_path: search_category_answers_path(@category)
    - else
      = render 'partials/search_form', search_path: search_answers_path

    = render @answers
    = will_paginate @answers

:javascript
  answers.init()
  window.search = new Search('#search')

  

app/views/answers/new.html.haml
%section.header
  .wrapper
    %h2 Create a new answer

%section.content.new
  .wrapper
    %p.back= link_to '‹‹ Go back', answers_path
    = render 'form'
    = render 'partials/markdown_legend'

app/views/answers/search.js.haml
var answers = "#{ escape_javascript(render @answers) }";
var $container = $('.content').children('.wrapper');

$container.find('.pagination').css('visibility','hidden');
$container.find('article').remove();

if (#{@noResults}) {
$container.append('<article><h1 class="no-results">No results</h1></article>');
} else {
if (#{@showAll}) $container.find('.pagination').css('visibility','visible');
$container.find('form').after(answers);
$container.children('.answer').first().addClass('active');
}

app/views/answers/show.html.haml
%section.header
  .wrapper

%section.content.show
  .wrapper
    %p.back= link_to '‹‹ Go back', category_answers_path(@answer.category)
    %h1= @answer.question
    .markdown
      %p= redcarpet @answer.content